export interface CompanyLogo {
  id: string;
  name: string;
  src: string;
}

/** 92 companies — colored SVGs in /public/companies/ (npm run company-logos:fetch) */
export const COMPANY_LOGOS: CompanyLogo[] = [
  { id: 'google', name: 'Google', src: '/companies/google.svg' },
  { id: 'microsoft', name: 'Microsoft', src: '/companies/microsoft.svg' },
  { id: 'amazon', name: 'Amazon', src: '/companies/amazon.svg' },
  { id: 'apple', name: 'Apple', src: '/companies/apple.svg' },
  { id: 'meta', name: 'Meta', src: '/companies/meta.svg' },
  { id: 'intel', name: 'Intel', src: '/companies/intel.svg' },
  { id: 'ibm', name: 'IBM', src: '/companies/ibm.svg' },
  { id: 'oracle', name: 'Oracle', src: '/companies/oracle.svg' },
  { id: 'salesforce', name: 'Salesforce', src: '/companies/salesforce.svg' },
  { id: 'adobe', name: 'Adobe', src: '/companies/adobe.svg' },
  { id: 'stripe', name: 'Stripe', src: '/companies/stripe.svg' },
  { id: 'paypal', name: 'PayPal', src: '/companies/paypal.svg' },
  { id: 'shopify', name: 'Shopify', src: '/companies/shopify.svg' },
  { id: 'uber', name: 'Uber', src: '/companies/uber.svg' },
  { id: 'airbnb', name: 'Airbnb', src: '/companies/airbnb.svg' },
  { id: 'spotify', name: 'Spotify', src: '/companies/spotify.svg' },
  { id: 'github', name: 'GitHub', src: '/companies/github.svg' },
  { id: 'slack', name: 'Slack', src: '/companies/slack.svg' },
  { id: 'zoom', name: 'Zoom', src: '/companies/zoom.svg' },
  { id: 'atlassian', name: 'Atlassian', src: '/companies/atlassian.svg' },
  { id: 'dropbox', name: 'Dropbox', src: '/companies/dropbox.svg' },
  { id: 'coinbase', name: 'Coinbase', src: '/companies/coinbase.svg' },
  { id: 'cisco', name: 'Cisco', src: '/companies/cisco.svg' },
  { id: 'sap', name: 'SAP', src: '/companies/sap.svg' },
  { id: 'walmart', name: 'Walmart', src: '/companies/walmart.svg' },
  // IT & AI
  { id: 'openai', name: 'OpenAI', src: '/companies/openai.svg' },
  { id: 'anthropic', name: 'Anthropic', src: '/companies/anthropic.svg' },
  { id: 'huggingface', name: 'Hugging Face', src: '/companies/huggingface.svg' },
  { id: 'deepmind', name: 'DeepMind', src: '/companies/deepmind.svg' },
  { id: 'perplexity', name: 'Perplexity', src: '/companies/perplexity.svg' },
  { id: 'replicate', name: 'Replicate', src: '/companies/replicate.svg' },
  { id: 'langchain', name: 'LangChain', src: '/companies/langchain.svg' },
  { id: 'weightsandbiases', name: 'Weights & Biases', src: '/companies/weightsandbiases.svg' },
  { id: 'databricks', name: 'Databricks', src: '/companies/databricks.svg' },
  { id: 'snowflake', name: 'Snowflake', src: '/companies/snowflake.svg' },
  { id: 'palantir', name: 'Palantir', src: '/companies/palantir.svg' },
  { id: 'datadog', name: 'Datadog', src: '/companies/datadog.svg' },
  { id: 'cloudflare', name: 'Cloudflare', src: '/companies/cloudflare.svg' },
  { id: 'docker', name: 'Docker', src: '/companies/docker.svg' },
  { id: 'mongodb', name: 'MongoDB', src: '/companies/mongodb.svg' },
  { id: 'redis', name: 'Redis', src: '/companies/redis.svg' },
  { id: 'vercel', name: 'Vercel', src: '/companies/vercel.svg' },
  { id: 'supabase', name: 'Supabase', src: '/companies/supabase.svg' },
  { id: 'googlecloud', name: 'Google Cloud', src: '/companies/googlecloud.svg' },
  { id: 'metaai', name: 'Meta AI', src: '/companies/metaai.svg' },
  // Software development & AI training
  { id: 'jetbrains', name: 'JetBrains', src: '/companies/jetbrains.svg' },
  { id: 'gitlab', name: 'GitLab', src: '/companies/gitlab.svg' },
  { id: 'figma', name: 'Figma', src: '/companies/figma.svg' },
  { id: 'twilio', name: 'Twilio', src: '/companies/twilio.svg' },
  { id: 'hashicorp', name: 'HashiCorp', src: '/companies/hashicorp.svg' },
  { id: 'elastic', name: 'Elastic', src: '/companies/elastic.svg' },
  { id: 'digitalocean', name: 'DigitalOcean', src: '/companies/digitalocean.svg' },
  { id: 'netlify', name: 'Netlify', src: '/companies/netlify.svg' },
  { id: 'postman', name: 'Postman', src: '/companies/postman.svg' },
  { id: 'prisma', name: 'Prisma', src: '/companies/prisma.svg' },
  { id: 'unity', name: 'Unity', src: '/companies/unity.svg' },
  { id: 'coursera', name: 'Coursera', src: '/companies/coursera.svg' },
  { id: 'udemy', name: 'Udemy', src: '/companies/udemy.svg' },
  { id: 'edx', name: 'edX', src: '/companies/edx.svg' },
  { id: 'datacamp', name: 'DataCamp', src: '/companies/datacamp.svg' },
  { id: 'codecademy', name: 'Codecademy', src: '/companies/codecademy.svg' },
  { id: 'freecodecamp', name: 'freeCodeCamp', src: '/companies/freecodecamp.svg' },
  { id: 'kaggle', name: 'Kaggle', src: '/companies/kaggle.svg' },
  { id: 'pluralsight', name: 'Pluralsight', src: '/companies/pluralsight.svg' },
  { id: 'anaconda', name: 'Anaconda', src: '/companies/anaconda.svg' },
  // Job boards & software outsourcing
  { id: 'indeed', name: 'Indeed', src: '/companies/indeed.svg' },
  { id: 'glassdoor', name: 'Glassdoor', src: '/companies/glassdoor.svg' },
  { id: 'monster', name: 'Monster', src: '/companies/monster.svg' },
  { id: 'wellfound', name: 'Wellfound', src: '/companies/wellfound.svg' },
  { id: 'angellist', name: 'AngelList', src: '/companies/angellist.svg' },
  { id: 'upwork', name: 'Upwork', src: '/companies/upwork.svg' },
  { id: 'fiverr', name: 'Fiverr', src: '/companies/fiverr.svg' },
  { id: 'freelancer', name: 'Freelancer', src: '/companies/freelancer.svg' },
  { id: 'toptal', name: 'Toptal', src: '/companies/toptal.svg' },
  { id: 'malt', name: 'Malt', src: '/companies/malt.svg' },
  { id: 'hackerrank', name: 'HackerRank', src: '/companies/hackerrank.svg' },
  { id: 'leetcode', name: 'LeetCode', src: '/companies/leetcode.svg' },
  { id: 'codewars', name: 'Codewars', src: '/companies/codewars.svg' },
  { id: 'andela', name: 'Andela', src: '/companies/andela.svg' },
  { id: 'arc', name: 'Arc.dev', src: '/companies/arc.svg' },
  { id: 'xing', name: 'Xing', src: '/companies/xing.svg' },
  { id: 'braintrust', name: 'Braintrust', src: '/companies/braintrust.svg' },
  { id: 'greenhouse', name: 'Greenhouse', src: '/companies/greenhouse.svg' },
  { id: '99designs', name: '99designs', src: '/companies/99designs.svg' },
  { id: 'polywork', name: 'Polywork', src: '/companies/polywork.svg' },
  { id: 'accenture', name: 'Accenture', src: '/companies/accenture.svg' },
  { id: 'cognizant', name: 'Cognizant', src: '/companies/cognizant.svg' },
  { id: 'infosys', name: 'Infosys', src: '/companies/infosys.svg' },
  { id: 'wipro', name: 'Wipro', src: '/companies/wipro.svg' },
  { id: 'hcl', name: 'HCL', src: '/companies/hcl.svg' },
  { id: 'tcs', name: 'TCS', src: '/companies/tcs.svg' },
  { id: 'persistent', name: 'Persistent', src: '/companies/persistent.svg' },
];
