/** Auto-generated by scripts/generate-devicon-stacks.mjs — do not edit manually */
export interface DeviconStack {
  id: string;
  label: string;
  iconClass: string;
}

/** 576 Devicon tech stacks (https://devicon.dev) */
export const DEVICON_STACKS: DeviconStack[] = [
  {
    "id": "aarch64",
    "label": "Aarch64",
    "iconClass": "devicon-aarch64-plain"
  },
  {
    "id": "adonisjs",
    "label": "Adonisjs",
    "iconClass": "devicon-adonisjs-original"
  },
  {
    "id": "aerospike",
    "label": "Aerospike",
    "iconClass": "devicon-aerospike-original"
  },
  {
    "id": "aframe",
    "label": "Aframe",
    "iconClass": "devicon-aframe-plain"
  },
  {
    "id": "aftereffects",
    "label": "Aftereffects",
    "iconClass": "devicon-aftereffects-plain"
  },
  {
    "id": "akka",
    "label": "Akka",
    "iconClass": "devicon-akka-plain"
  },
  {
    "id": "algolia",
    "label": "Algolia",
    "iconClass": "devicon-algolia-original"
  },
  {
    "id": "almalinux",
    "label": "Almalinux",
    "iconClass": "devicon-almalinux-plain"
  },
  {
    "id": "alpinejs",
    "label": "Alpinejs",
    "iconClass": "devicon-alpinejs-original"
  },
  {
    "id": "amazonwebservices",
    "label": "Amazonwebservices",
    "iconClass": "devicon-amazonwebservices-plain-wordmark"
  },
  {
    "id": "anaconda",
    "label": "Anaconda",
    "iconClass": "devicon-anaconda-original"
  },
  {
    "id": "android",
    "label": "Android",
    "iconClass": "devicon-android-plain"
  },
  {
    "id": "androidstudio",
    "label": "Androidstudio",
    "iconClass": "devicon-androidstudio-plain"
  },
  {
    "id": "angular",
    "label": "Angular",
    "iconClass": "devicon-angular-plain"
  },
  {
    "id": "angularjs",
    "label": "Angularjs",
    "iconClass": "devicon-angularjs-plain"
  },
  {
    "id": "angularmaterial",
    "label": "Angularmaterial",
    "iconClass": "devicon-angularmaterial-plain"
  },
  {
    "id": "ansible",
    "label": "Ansible",
    "iconClass": "devicon-ansible-plain"
  },
  {
    "id": "ansys",
    "label": "Ansys",
    "iconClass": "devicon-ansys-plain"
  },
  {
    "id": "antdesign",
    "label": "Antdesign",
    "iconClass": "devicon-antdesign-plain"
  },
  {
    "id": "apache",
    "label": "Apache",
    "iconClass": "devicon-apache-plain"
  },
  {
    "id": "apacheairflow",
    "label": "Apacheairflow",
    "iconClass": "devicon-apacheairflow-plain"
  },
  {
    "id": "apachekafka",
    "label": "Apachekafka",
    "iconClass": "devicon-apachekafka-original"
  },
  {
    "id": "apachespark",
    "label": "Apachespark",
    "iconClass": "devicon-apachespark-original"
  },
  {
    "id": "apex",
    "label": "Apex",
    "iconClass": "devicon-apex-original"
  },
  {
    "id": "apl",
    "label": "Apl",
    "iconClass": "devicon-apl-plain"
  },
  {
    "id": "apollographql",
    "label": "Apollographql",
    "iconClass": "devicon-apollographql-original"
  },
  {
    "id": "appcelerator",
    "label": "Appcelerator",
    "iconClass": "devicon-appcelerator-original"
  },
  {
    "id": "apple",
    "label": "Apple",
    "iconClass": "devicon-apple-original"
  },
  {
    "id": "appwrite",
    "label": "Appwrite",
    "iconClass": "devicon-appwrite-original"
  },
  {
    "id": "archlinux",
    "label": "Archlinux",
    "iconClass": "devicon-archlinux-plain"
  },
  {
    "id": "arduino",
    "label": "Arduino",
    "iconClass": "devicon-arduino-plain"
  },
  {
    "id": "argocd",
    "label": "Argocd",
    "iconClass": "devicon-argocd-plain"
  },
  {
    "id": "artixlinux",
    "label": "Artixlinux",
    "iconClass": "devicon-artixlinux-plain"
  },
  {
    "id": "astro",
    "label": "Astro",
    "iconClass": "devicon-astro-plain"
  },
  {
    "id": "atom",
    "label": "Atom",
    "iconClass": "devicon-atom-original"
  },
  {
    "id": "awk",
    "label": "Awk",
    "iconClass": "devicon-awk-plain-wordmark"
  },
  {
    "id": "axios",
    "label": "Axios",
    "iconClass": "devicon-axios-plain"
  },
  {
    "id": "azure",
    "label": "Azure",
    "iconClass": "devicon-azure-plain"
  },
  {
    "id": "azuredevops",
    "label": "Azuredevops",
    "iconClass": "devicon-azuredevops-plain"
  },
  {
    "id": "azuresqldatabase",
    "label": "Azuresqldatabase",
    "iconClass": "devicon-azuresqldatabase-plain"
  },
  {
    "id": "babel",
    "label": "Babel",
    "iconClass": "devicon-babel-plain"
  },
  {
    "id": "babylonjs",
    "label": "Babylonjs",
    "iconClass": "devicon-babylonjs-plain"
  },
  {
    "id": "backbonejs",
    "label": "Backbonejs",
    "iconClass": "devicon-backbonejs-plain"
  },
  {
    "id": "ballerina",
    "label": "Ballerina",
    "iconClass": "devicon-ballerina-original"
  },
  {
    "id": "bamboo",
    "label": "Bamboo",
    "iconClass": "devicon-bamboo-original"
  },
  {
    "id": "bash",
    "label": "Bash",
    "iconClass": "devicon-bash-plain"
  },
  {
    "id": "bazel",
    "label": "Bazel",
    "iconClass": "devicon-bazel-plain"
  },
  {
    "id": "beats",
    "label": "Beats",
    "iconClass": "devicon-beats-plain"
  },
  {
    "id": "behance",
    "label": "Behance",
    "iconClass": "devicon-behance-plain"
  },
  {
    "id": "bevyengine",
    "label": "Bevyengine",
    "iconClass": "devicon-bevyengine-plain"
  },
  {
    "id": "biome",
    "label": "Biome",
    "iconClass": "devicon-biome-original"
  },
  {
    "id": "bitbucket",
    "label": "Bitbucket",
    "iconClass": "devicon-bitbucket-original"
  },
  {
    "id": "blazor",
    "label": "Blazor",
    "iconClass": "devicon-blazor-original"
  },
  {
    "id": "blender",
    "label": "Blender",
    "iconClass": "devicon-blender-original"
  },
  {
    "id": "bootstrap",
    "label": "Bootstrap",
    "iconClass": "devicon-bootstrap-plain"
  },
  {
    "id": "bower",
    "label": "Bower",
    "iconClass": "devicon-bower-plain"
  },
  {
    "id": "browserstack",
    "label": "Browserstack",
    "iconClass": "devicon-browserstack-plain"
  },
  {
    "id": "bulma",
    "label": "Bulma",
    "iconClass": "devicon-bulma-plain"
  },
  {
    "id": "bun",
    "label": "Bun",
    "iconClass": "devicon-bun-plain"
  },
  {
    "id": "c",
    "label": "C",
    "iconClass": "devicon-c-original"
  },
  {
    "id": "cairo",
    "label": "Cairo",
    "iconClass": "devicon-cairo-plain"
  },
  {
    "id": "cakephp",
    "label": "Cakephp",
    "iconClass": "devicon-cakephp-plain"
  },
  {
    "id": "canva",
    "label": "Canva",
    "iconClass": "devicon-canva-original"
  },
  {
    "id": "capacitor",
    "label": "Capacitor",
    "iconClass": "devicon-capacitor-plain"
  },
  {
    "id": "carbon",
    "label": "Carbon",
    "iconClass": "devicon-carbon-original"
  },
  {
    "id": "cassandra",
    "label": "Cassandra",
    "iconClass": "devicon-cassandra-plain"
  },
  {
    "id": "centos",
    "label": "Centos",
    "iconClass": "devicon-centos-plain"
  },
  {
    "id": "ceylon",
    "label": "Ceylon",
    "iconClass": "devicon-ceylon-plain"
  },
  {
    "id": "chakraui",
    "label": "Chakraui",
    "iconClass": "devicon-chakraui-plain"
  },
  {
    "id": "chartjs",
    "label": "Chartjs",
    "iconClass": "devicon-chartjs-plain"
  },
  {
    "id": "chrome",
    "label": "Chrome",
    "iconClass": "devicon-chrome-plain"
  },
  {
    "id": "circleci",
    "label": "Circleci",
    "iconClass": "devicon-circleci-plain"
  },
  {
    "id": "clarity",
    "label": "Clarity",
    "iconClass": "devicon-clarity-plain"
  },
  {
    "id": "clickhouse",
    "label": "Clickhouse",
    "iconClass": "devicon-clickhouse-plain"
  },
  {
    "id": "clion",
    "label": "Clion",
    "iconClass": "devicon-clion-plain"
  },
  {
    "id": "clojure",
    "label": "Clojure",
    "iconClass": "devicon-clojure-plain"
  },
  {
    "id": "clojurescript",
    "label": "Clojurescript",
    "iconClass": "devicon-clojurescript-plain"
  },
  {
    "id": "cloudflare",
    "label": "Cloudflare",
    "iconClass": "devicon-cloudflare-plain"
  },
  {
    "id": "cloudflareworkers",
    "label": "Cloudflareworkers",
    "iconClass": "devicon-cloudflareworkers-plain"
  },
  {
    "id": "cloudrun",
    "label": "Cloudrun",
    "iconClass": "devicon-cloudrun-plain"
  },
  {
    "id": "cmake",
    "label": "Cmake",
    "iconClass": "devicon-cmake-plain"
  },
  {
    "id": "cobol",
    "label": "Cobol",
    "iconClass": "devicon-cobol-original"
  },
  {
    "id": "codeac",
    "label": "Codeac",
    "iconClass": "devicon-codeac-original"
  },
  {
    "id": "codecov",
    "label": "Codecov",
    "iconClass": "devicon-codecov-plain"
  },
  {
    "id": "codeigniter",
    "label": "Codeigniter",
    "iconClass": "devicon-codeigniter-plain"
  },
  {
    "id": "codepen",
    "label": "Codepen",
    "iconClass": "devicon-codepen-original"
  },
  {
    "id": "coffeescript",
    "label": "Coffeescript",
    "iconClass": "devicon-coffeescript-original"
  },
  {
    "id": "composer",
    "label": "Composer",
    "iconClass": "devicon-composer-line"
  },
  {
    "id": "confluence",
    "label": "Confluence",
    "iconClass": "devicon-confluence-plain"
  },
  {
    "id": "consul",
    "label": "Consul",
    "iconClass": "devicon-consul-original"
  },
  {
    "id": "contao",
    "label": "Contao",
    "iconClass": "devicon-contao-original"
  },
  {
    "id": "corejs",
    "label": "Corejs",
    "iconClass": "devicon-corejs-original"
  },
  {
    "id": "cosmosdb",
    "label": "Cosmosdb",
    "iconClass": "devicon-cosmosdb-plain"
  },
  {
    "id": "couchbase",
    "label": "Couchbase",
    "iconClass": "devicon-couchbase-original"
  },
  {
    "id": "couchdb",
    "label": "Couchdb",
    "iconClass": "devicon-couchdb-plain"
  },
  {
    "id": "cpanel",
    "label": "Cpanel",
    "iconClass": "devicon-cpanel-original"
  },
  {
    "id": "cplusplus",
    "label": "Cplusplus",
    "iconClass": "devicon-cplusplus-plain"
  },
  {
    "id": "crystal",
    "label": "Crystal",
    "iconClass": "devicon-crystal-original"
  },
  {
    "id": "csharp",
    "label": "Csharp",
    "iconClass": "devicon-csharp-plain"
  },
  {
    "id": "css3",
    "label": "Css3",
    "iconClass": "devicon-css3-plain"
  },
  {
    "id": "cucumber",
    "label": "Cucumber",
    "iconClass": "devicon-cucumber-plain"
  },
  {
    "id": "cypressio",
    "label": "Cypressio",
    "iconClass": "devicon-cypressio-plain"
  },
  {
    "id": "d3js",
    "label": "D3js",
    "iconClass": "devicon-d3js-plain"
  },
  {
    "id": "dart",
    "label": "Dart",
    "iconClass": "devicon-dart-plain"
  },
  {
    "id": "datadog",
    "label": "Datadog",
    "iconClass": "devicon-datadog-original"
  },
  {
    "id": "datagrip",
    "label": "Datagrip",
    "iconClass": "devicon-datagrip-plain"
  },
  {
    "id": "dataspell",
    "label": "Dataspell",
    "iconClass": "devicon-dataspell-plain"
  },
  {
    "id": "datatables",
    "label": "Datatables",
    "iconClass": "devicon-datatables-original"
  },
  {
    "id": "dbeaver",
    "label": "Dbeaver",
    "iconClass": "devicon-dbeaver-plain"
  },
  {
    "id": "debian",
    "label": "Debian",
    "iconClass": "devicon-debian-plain"
  },
  {
    "id": "delphi",
    "label": "Delphi",
    "iconClass": "devicon-delphi-plain"
  },
  {
    "id": "denojs",
    "label": "Denojs",
    "iconClass": "devicon-denojs-original"
  },
  {
    "id": "detaspace",
    "label": "Detaspace",
    "iconClass": "devicon-detaspace-line"
  },
  {
    "id": "devicon",
    "label": "Devicon",
    "iconClass": "devicon-devicon-plain"
  },
  {
    "id": "digitalocean",
    "label": "Digitalocean",
    "iconClass": "devicon-digitalocean-original"
  },
  {
    "id": "discloud",
    "label": "Discloud",
    "iconClass": "devicon-discloud-original"
  },
  {
    "id": "discordjs",
    "label": "Discordjs",
    "iconClass": "devicon-discordjs-plain"
  },
  {
    "id": "django",
    "label": "Django",
    "iconClass": "devicon-django-plain"
  },
  {
    "id": "djangorest",
    "label": "Djangorest",
    "iconClass": "devicon-djangorest-plain"
  },
  {
    "id": "docker",
    "label": "Docker",
    "iconClass": "devicon-docker-plain"
  },
  {
    "id": "doctrine",
    "label": "Doctrine",
    "iconClass": "devicon-doctrine-plain"
  },
  {
    "id": "dot-net",
    "label": "Dot Net",
    "iconClass": "devicon-dot-net-plain"
  },
  {
    "id": "dotnetcore",
    "label": "Dotnetcore",
    "iconClass": "devicon-dotnetcore-plain"
  },
  {
    "id": "dovecot",
    "label": "Dovecot",
    "iconClass": "devicon-dovecot-plain"
  },
  {
    "id": "dreamweaver",
    "label": "Dreamweaver",
    "iconClass": "devicon-dreamweaver-plain"
  },
  {
    "id": "dropwizard",
    "label": "Dropwizard",
    "iconClass": "devicon-dropwizard-plain"
  },
  {
    "id": "drupal",
    "label": "Drupal",
    "iconClass": "devicon-drupal-plain"
  },
  {
    "id": "duckdb",
    "label": "Duckdb",
    "iconClass": "devicon-duckdb-plain"
  },
  {
    "id": "dyalog",
    "label": "Dyalog",
    "iconClass": "devicon-dyalog-plain"
  },
  {
    "id": "dynamodb",
    "label": "Dynamodb",
    "iconClass": "devicon-dynamodb-plain"
  },
  {
    "id": "dynatrace",
    "label": "Dynatrace",
    "iconClass": "devicon-dynatrace-plain"
  },
  {
    "id": "eclipse",
    "label": "Eclipse",
    "iconClass": "devicon-eclipse-plain"
  },
  {
    "id": "ecto",
    "label": "Ecto",
    "iconClass": "devicon-ecto-original"
  },
  {
    "id": "elasticsearch",
    "label": "Elasticsearch",
    "iconClass": "devicon-elasticsearch-plain"
  },
  {
    "id": "electron",
    "label": "Electron",
    "iconClass": "devicon-electron-original"
  },
  {
    "id": "eleventy",
    "label": "Eleventy",
    "iconClass": "devicon-eleventy-plain"
  },
  {
    "id": "elixir",
    "label": "Elixir",
    "iconClass": "devicon-elixir-plain"
  },
  {
    "id": "elm",
    "label": "Elm",
    "iconClass": "devicon-elm-plain"
  },
  {
    "id": "emacs",
    "label": "Emacs",
    "iconClass": "devicon-emacs-original"
  },
  {
    "id": "embeddedc",
    "label": "Embeddedc",
    "iconClass": "devicon-embeddedc-plain"
  },
  {
    "id": "ember",
    "label": "Ember",
    "iconClass": "devicon-ember-plain"
  },
  {
    "id": "entityframeworkcore",
    "label": "Entityframeworkcore",
    "iconClass": "devicon-entityframeworkcore-plain"
  },
  {
    "id": "envoy",
    "label": "Envoy",
    "iconClass": "devicon-envoy-plain"
  },
  {
    "id": "erlang",
    "label": "Erlang",
    "iconClass": "devicon-erlang-plain"
  },
  {
    "id": "eslint",
    "label": "Eslint",
    "iconClass": "devicon-eslint-plain"
  },
  {
    "id": "expo",
    "label": "Expo",
    "iconClass": "devicon-expo-original"
  },
  {
    "id": "express",
    "label": "Express",
    "iconClass": "devicon-express-original"
  },
  {
    "id": "facebook",
    "label": "Facebook",
    "iconClass": "devicon-facebook-plain"
  },
  {
    "id": "fastapi",
    "label": "Fastapi",
    "iconClass": "devicon-fastapi-plain"
  },
  {
    "id": "fastify",
    "label": "Fastify",
    "iconClass": "devicon-fastify-plain"
  },
  {
    "id": "faunadb",
    "label": "Faunadb",
    "iconClass": "devicon-faunadb-original"
  },
  {
    "id": "feathersjs",
    "label": "Feathersjs",
    "iconClass": "devicon-feathersjs-original"
  },
  {
    "id": "fedora",
    "label": "Fedora",
    "iconClass": "devicon-fedora-plain"
  },
  {
    "id": "fiber",
    "label": "Fiber",
    "iconClass": "devicon-fiber-plain"
  },
  {
    "id": "figma",
    "label": "Figma",
    "iconClass": "devicon-figma-plain"
  },
  {
    "id": "filamentphp",
    "label": "Filamentphp",
    "iconClass": "devicon-filamentphp-original"
  },
  {
    "id": "filezilla",
    "label": "Filezilla",
    "iconClass": "devicon-filezilla-plain"
  },
  {
    "id": "firebase",
    "label": "Firebase",
    "iconClass": "devicon-firebase-plain"
  },
  {
    "id": "firebird",
    "label": "Firebird",
    "iconClass": "devicon-firebird-plain"
  },
  {
    "id": "firefox",
    "label": "Firefox",
    "iconClass": "devicon-firefox-plain"
  },
  {
    "id": "flask",
    "label": "Flask",
    "iconClass": "devicon-flask-original"
  },
  {
    "id": "flutter",
    "label": "Flutter",
    "iconClass": "devicon-flutter-plain"
  },
  {
    "id": "forgejo",
    "label": "Forgejo",
    "iconClass": "devicon-forgejo-plain"
  },
  {
    "id": "fortran",
    "label": "Fortran",
    "iconClass": "devicon-fortran-original"
  },
  {
    "id": "foundation",
    "label": "Foundation",
    "iconClass": "devicon-foundation-plain"
  },
  {
    "id": "framermotion",
    "label": "Framermotion",
    "iconClass": "devicon-framermotion-original"
  },
  {
    "id": "framework7",
    "label": "Framework7",
    "iconClass": "devicon-framework7-original"
  },
  {
    "id": "fsharp",
    "label": "Fsharp",
    "iconClass": "devicon-fsharp-plain"
  },
  {
    "id": "fusion",
    "label": "Fusion",
    "iconClass": "devicon-fusion-plain"
  },
  {
    "id": "gardener",
    "label": "Gardener",
    "iconClass": "devicon-gardener-plain"
  },
  {
    "id": "gatling",
    "label": "Gatling",
    "iconClass": "devicon-gatling-original"
  },
  {
    "id": "gatsby",
    "label": "Gatsby",
    "iconClass": "devicon-gatsby-original"
  },
  {
    "id": "gazebo",
    "label": "Gazebo",
    "iconClass": "devicon-gazebo-plain"
  },
  {
    "id": "gcc",
    "label": "Gcc",
    "iconClass": "devicon-gcc-plain"
  },
  {
    "id": "gentoo",
    "label": "Gentoo",
    "iconClass": "devicon-gentoo-plain"
  },
  {
    "id": "ghost",
    "label": "Ghost",
    "iconClass": "devicon-ghost-original"
  },
  {
    "id": "gimp",
    "label": "Gimp",
    "iconClass": "devicon-gimp-plain"
  },
  {
    "id": "git",
    "label": "Git",
    "iconClass": "devicon-git-plain"
  },
  {
    "id": "gitbook",
    "label": "Gitbook",
    "iconClass": "devicon-gitbook-original"
  },
  {
    "id": "github",
    "label": "Github",
    "iconClass": "devicon-github-original"
  },
  {
    "id": "githubactions",
    "label": "Githubactions",
    "iconClass": "devicon-githubactions-plain"
  },
  {
    "id": "githubcodespaces",
    "label": "Githubcodespaces",
    "iconClass": "devicon-githubcodespaces-plain"
  },
  {
    "id": "gitkraken",
    "label": "Gitkraken",
    "iconClass": "devicon-gitkraken-original"
  },
  {
    "id": "gitlab",
    "label": "Gitlab",
    "iconClass": "devicon-gitlab-plain"
  },
  {
    "id": "gitpod",
    "label": "Gitpod",
    "iconClass": "devicon-gitpod-plain"
  },
  {
    "id": "gitter",
    "label": "Gitter",
    "iconClass": "devicon-gitter-plain"
  },
  {
    "id": "gleam",
    "label": "Gleam",
    "iconClass": "devicon-gleam-plain"
  },
  {
    "id": "glitch",
    "label": "Glitch",
    "iconClass": "devicon-glitch-plain"
  },
  {
    "id": "go",
    "label": "Go",
    "iconClass": "devicon-go-plain"
  },
  {
    "id": "godot",
    "label": "Godot",
    "iconClass": "devicon-godot-plain"
  },
  {
    "id": "goland",
    "label": "Goland",
    "iconClass": "devicon-goland-plain"
  },
  {
    "id": "google",
    "label": "Google",
    "iconClass": "devicon-google-plain"
  },
  {
    "id": "googlecloud",
    "label": "Googlecloud",
    "iconClass": "devicon-googlecloud-plain"
  },
  {
    "id": "googlecolab",
    "label": "Googlecolab",
    "iconClass": "devicon-googlecolab-plain"
  },
  {
    "id": "gradle",
    "label": "Gradle",
    "iconClass": "devicon-gradle-original"
  },
  {
    "id": "grafana",
    "label": "Grafana",
    "iconClass": "devicon-grafana-plain"
  },
  {
    "id": "grails",
    "label": "Grails",
    "iconClass": "devicon-grails-plain"
  },
  {
    "id": "graphql",
    "label": "Graphql",
    "iconClass": "devicon-graphql-plain"
  },
  {
    "id": "groovy",
    "label": "Groovy",
    "iconClass": "devicon-groovy-plain"
  },
  {
    "id": "grpc",
    "label": "Grpc",
    "iconClass": "devicon-grpc-plain"
  },
  {
    "id": "grunt",
    "label": "Grunt",
    "iconClass": "devicon-grunt-plain"
  },
  {
    "id": "gulp",
    "label": "Gulp",
    "iconClass": "devicon-gulp-plain"
  },
  {
    "id": "hadoop",
    "label": "Hadoop",
    "iconClass": "devicon-hadoop-plain"
  },
  {
    "id": "handlebars",
    "label": "Handlebars",
    "iconClass": "devicon-handlebars-original"
  },
  {
    "id": "harbor",
    "label": "Harbor",
    "iconClass": "devicon-harbor-plain"
  },
  {
    "id": "hardhat",
    "label": "Hardhat",
    "iconClass": "devicon-hardhat-plain"
  },
  {
    "id": "harvester",
    "label": "Harvester",
    "iconClass": "devicon-harvester-original"
  },
  {
    "id": "haskell",
    "label": "Haskell",
    "iconClass": "devicon-haskell-plain"
  },
  {
    "id": "haxe",
    "label": "Haxe",
    "iconClass": "devicon-haxe-plain"
  },
  {
    "id": "helm",
    "label": "Helm",
    "iconClass": "devicon-helm-original"
  },
  {
    "id": "heroku",
    "label": "Heroku",
    "iconClass": "devicon-heroku-original"
  },
  {
    "id": "hibernate",
    "label": "Hibernate",
    "iconClass": "devicon-hibernate-plain"
  },
  {
    "id": "homebrew",
    "label": "Homebrew",
    "iconClass": "devicon-homebrew-plain"
  },
  {
    "id": "hoppscotch",
    "label": "Hoppscotch",
    "iconClass": "devicon-hoppscotch-plain"
  },
  {
    "id": "html5",
    "label": "Html5",
    "iconClass": "devicon-html5-plain"
  },
  {
    "id": "htmx",
    "label": "Htmx",
    "iconClass": "devicon-htmx-plain"
  },
  {
    "id": "hugo",
    "label": "Hugo",
    "iconClass": "devicon-hugo-plain"
  },
  {
    "id": "hyperv",
    "label": "Hyperv",
    "iconClass": "devicon-hyperv-plain"
  },
  {
    "id": "ie10",
    "label": "Ie10",
    "iconClass": "devicon-ie10-original"
  },
  {
    "id": "ifttt",
    "label": "Ifttt",
    "iconClass": "devicon-ifttt-original"
  },
  {
    "id": "illustrator",
    "label": "Illustrator",
    "iconClass": "devicon-illustrator-plain"
  },
  {
    "id": "inertiajs",
    "label": "Inertiajs",
    "iconClass": "devicon-inertiajs-plain"
  },
  {
    "id": "influxdb",
    "label": "Influxdb",
    "iconClass": "devicon-influxdb-original"
  },
  {
    "id": "inkscape",
    "label": "Inkscape",
    "iconClass": "devicon-inkscape-plain"
  },
  {
    "id": "insomnia",
    "label": "Insomnia",
    "iconClass": "devicon-insomnia-plain"
  },
  {
    "id": "intellij",
    "label": "Intellij",
    "iconClass": "devicon-intellij-plain"
  },
  {
    "id": "ionic",
    "label": "Ionic",
    "iconClass": "devicon-ionic-original"
  },
  {
    "id": "jaegertracing",
    "label": "Jaegertracing",
    "iconClass": "devicon-jaegertracing-plain"
  },
  {
    "id": "jamstack",
    "label": "Jamstack",
    "iconClass": "devicon-jamstack-original"
  },
  {
    "id": "jasmine",
    "label": "Jasmine",
    "iconClass": "devicon-jasmine-original"
  },
  {
    "id": "java",
    "label": "Java",
    "iconClass": "devicon-java-plain"
  },
  {
    "id": "javascript",
    "label": "Javascript",
    "iconClass": "devicon-javascript-plain"
  },
  {
    "id": "jeet",
    "label": "Jeet",
    "iconClass": "devicon-jeet-plain"
  },
  {
    "id": "jekyll",
    "label": "Jekyll",
    "iconClass": "devicon-jekyll-plain"
  },
  {
    "id": "jenkins",
    "label": "Jenkins",
    "iconClass": "devicon-jenkins-plain"
  },
  {
    "id": "jest",
    "label": "Jest",
    "iconClass": "devicon-jest-plain"
  },
  {
    "id": "jetbrains",
    "label": "Jetbrains",
    "iconClass": "devicon-jetbrains-plain"
  },
  {
    "id": "jetpackcompose",
    "label": "Jetpackcompose",
    "iconClass": "devicon-jetpackcompose-plain"
  },
  {
    "id": "jhipster",
    "label": "Jhipster",
    "iconClass": "devicon-jhipster-plain"
  },
  {
    "id": "jira",
    "label": "Jira",
    "iconClass": "devicon-jira-plain"
  },
  {
    "id": "jiraalign",
    "label": "Jiraalign",
    "iconClass": "devicon-jiraalign-plain"
  },
  {
    "id": "jquery",
    "label": "Jquery",
    "iconClass": "devicon-jquery-plain"
  },
  {
    "id": "json",
    "label": "Json",
    "iconClass": "devicon-json-plain"
  },
  {
    "id": "jule",
    "label": "Jule",
    "iconClass": "devicon-jule-original"
  },
  {
    "id": "julia",
    "label": "Julia",
    "iconClass": "devicon-julia-plain"
  },
  {
    "id": "junit",
    "label": "Junit",
    "iconClass": "devicon-junit-plain"
  },
  {
    "id": "jupyter",
    "label": "Jupyter",
    "iconClass": "devicon-jupyter-plain"
  },
  {
    "id": "k3os",
    "label": "K3os",
    "iconClass": "devicon-k3os-original"
  },
  {
    "id": "k3s",
    "label": "K3s",
    "iconClass": "devicon-k3s-original"
  },
  {
    "id": "k6",
    "label": "K6",
    "iconClass": "devicon-k6-original"
  },
  {
    "id": "kaggle",
    "label": "Kaggle",
    "iconClass": "devicon-kaggle-original"
  },
  {
    "id": "kaldi",
    "label": "Kaldi",
    "iconClass": "devicon-kaldi-plain"
  },
  {
    "id": "kalilinux",
    "label": "Kalilinux",
    "iconClass": "devicon-kalilinux-original"
  },
  {
    "id": "karatelabs",
    "label": "Karatelabs",
    "iconClass": "devicon-karatelabs-plain"
  },
  {
    "id": "karma",
    "label": "Karma",
    "iconClass": "devicon-karma-plain"
  },
  {
    "id": "kdeneon",
    "label": "Kdeneon",
    "iconClass": "devicon-kdeneon-plain"
  },
  {
    "id": "keras",
    "label": "Keras",
    "iconClass": "devicon-keras-plain"
  },
  {
    "id": "kibana",
    "label": "Kibana",
    "iconClass": "devicon-kibana-plain"
  },
  {
    "id": "knexjs",
    "label": "Knexjs",
    "iconClass": "devicon-knexjs-original"
  },
  {
    "id": "knockout",
    "label": "Knockout",
    "iconClass": "devicon-knockout-plain-wordmark"
  },
  {
    "id": "kotlin",
    "label": "Kotlin",
    "iconClass": "devicon-kotlin-plain"
  },
  {
    "id": "krakenjs",
    "label": "Krakenjs",
    "iconClass": "devicon-krakenjs-plain"
  },
  {
    "id": "ktor",
    "label": "Ktor",
    "iconClass": "devicon-ktor-plain"
  },
  {
    "id": "kubeflow",
    "label": "Kubeflow",
    "iconClass": "devicon-kubeflow-plain"
  },
  {
    "id": "kubernetes",
    "label": "Kubernetes",
    "iconClass": "devicon-kubernetes-plain"
  },
  {
    "id": "labview",
    "label": "Labview",
    "iconClass": "devicon-labview-plain"
  },
  {
    "id": "laminas",
    "label": "Laminas",
    "iconClass": "devicon-laminas-original"
  },
  {
    "id": "laravel",
    "label": "Laravel",
    "iconClass": "devicon-laravel-original"
  },
  {
    "id": "laraveljetstream",
    "label": "Laraveljetstream",
    "iconClass": "devicon-laraveljetstream-original"
  },
  {
    "id": "latex",
    "label": "Latex",
    "iconClass": "devicon-latex-original"
  },
  {
    "id": "leetcode",
    "label": "Leetcode",
    "iconClass": "devicon-leetcode-plain"
  },
  {
    "id": "less",
    "label": "Less",
    "iconClass": "devicon-less-plain-wordmark"
  },
  {
    "id": "libgdx",
    "label": "Libgdx",
    "iconClass": "devicon-libgdx-plain"
  },
  {
    "id": "linkedin",
    "label": "Linkedin",
    "iconClass": "devicon-linkedin-plain"
  },
  {
    "id": "linux",
    "label": "Linux",
    "iconClass": "devicon-linux-plain"
  },
  {
    "id": "linuxmint",
    "label": "Linuxmint",
    "iconClass": "devicon-linuxmint-plain"
  },
  {
    "id": "liquibase",
    "label": "Liquibase",
    "iconClass": "devicon-liquibase-original"
  },
  {
    "id": "livewire",
    "label": "Livewire",
    "iconClass": "devicon-livewire-plain"
  },
  {
    "id": "llvm",
    "label": "Llvm",
    "iconClass": "devicon-llvm-plain"
  },
  {
    "id": "lodash",
    "label": "Lodash",
    "iconClass": "devicon-lodash-plain"
  },
  {
    "id": "logstash",
    "label": "Logstash",
    "iconClass": "devicon-logstash-plain"
  },
  {
    "id": "love2d",
    "label": "Love2d",
    "iconClass": "devicon-love2d-plain"
  },
  {
    "id": "lua",
    "label": "Lua",
    "iconClass": "devicon-lua-plain"
  },
  {
    "id": "lumen",
    "label": "Lumen",
    "iconClass": "devicon-lumen-original"
  },
  {
    "id": "magento",
    "label": "Magento",
    "iconClass": "devicon-magento-original"
  },
  {
    "id": "mapbox",
    "label": "Mapbox",
    "iconClass": "devicon-mapbox-original"
  },
  {
    "id": "mariadb",
    "label": "Mariadb",
    "iconClass": "devicon-mariadb-original"
  },
  {
    "id": "markdown",
    "label": "Markdown",
    "iconClass": "devicon-markdown-original"
  },
  {
    "id": "materializecss",
    "label": "Materializecss",
    "iconClass": "devicon-materializecss-plain"
  },
  {
    "id": "materialui",
    "label": "Materialui",
    "iconClass": "devicon-materialui-plain"
  },
  {
    "id": "matlab",
    "label": "Matlab",
    "iconClass": "devicon-matlab-plain"
  },
  {
    "id": "matplotlib",
    "label": "Matplotlib",
    "iconClass": "devicon-matplotlib-plain"
  },
  {
    "id": "mattermost",
    "label": "Mattermost",
    "iconClass": "devicon-mattermost-original"
  },
  {
    "id": "maven",
    "label": "Maven",
    "iconClass": "devicon-maven-plain"
  },
  {
    "id": "maya",
    "label": "Maya",
    "iconClass": "devicon-maya-plain"
  },
  {
    "id": "memcached",
    "label": "Memcached",
    "iconClass": "devicon-memcached-plain"
  },
  {
    "id": "mercurial",
    "label": "Mercurial",
    "iconClass": "devicon-mercurial-plain"
  },
  {
    "id": "meteor",
    "label": "Meteor",
    "iconClass": "devicon-meteor-plain"
  },
  {
    "id": "microsoftsqlserver",
    "label": "Microsoftsqlserver",
    "iconClass": "devicon-microsoftsqlserver-plain"
  },
  {
    "id": "minitab",
    "label": "Minitab",
    "iconClass": "devicon-minitab-plain"
  },
  {
    "id": "mithril",
    "label": "Mithril",
    "iconClass": "devicon-mithril-original"
  },
  {
    "id": "mobx",
    "label": "Mobx",
    "iconClass": "devicon-mobx-plain"
  },
  {
    "id": "mocha",
    "label": "Mocha",
    "iconClass": "devicon-mocha-plain"
  },
  {
    "id": "modx",
    "label": "Modx",
    "iconClass": "devicon-modx-plain"
  },
  {
    "id": "moleculer",
    "label": "Moleculer",
    "iconClass": "devicon-moleculer-original"
  },
  {
    "id": "mongodb",
    "label": "Mongodb",
    "iconClass": "devicon-mongodb-plain"
  },
  {
    "id": "mongoose",
    "label": "Mongoose",
    "iconClass": "devicon-mongoose-original"
  },
  {
    "id": "monogame",
    "label": "Monogame",
    "iconClass": "devicon-monogame-original"
  },
  {
    "id": "moodle",
    "label": "Moodle",
    "iconClass": "devicon-moodle-plain"
  },
  {
    "id": "msdos",
    "label": "Msdos",
    "iconClass": "devicon-msdos-plain"
  },
  {
    "id": "mysql",
    "label": "Mysql",
    "iconClass": "devicon-mysql-original"
  },
  {
    "id": "nano",
    "label": "Nano",
    "iconClass": "devicon-nano-plain"
  },
  {
    "id": "nats",
    "label": "Nats",
    "iconClass": "devicon-nats-plain"
  },
  {
    "id": "neo4j",
    "label": "Neo4j",
    "iconClass": "devicon-neo4j-plain"
  },
  {
    "id": "neovim",
    "label": "Neovim",
    "iconClass": "devicon-neovim-plain"
  },
  {
    "id": "nestjs",
    "label": "Nestjs",
    "iconClass": "devicon-nestjs-original"
  },
  {
    "id": "netbeans",
    "label": "Netbeans",
    "iconClass": "devicon-netbeans-plain"
  },
  {
    "id": "netbox",
    "label": "Netbox",
    "iconClass": "devicon-netbox-plain"
  },
  {
    "id": "netlify",
    "label": "Netlify",
    "iconClass": "devicon-netlify-plain"
  },
  {
    "id": "networkx",
    "label": "Networkx",
    "iconClass": "devicon-networkx-plain"
  },
  {
    "id": "newrelic",
    "label": "Newrelic",
    "iconClass": "devicon-newrelic-plain"
  },
  {
    "id": "nextjs",
    "label": "Nextjs",
    "iconClass": "devicon-nextjs-plain"
  },
  {
    "id": "nginx",
    "label": "Nginx",
    "iconClass": "devicon-nginx-original"
  },
  {
    "id": "ngrok",
    "label": "Ngrok",
    "iconClass": "devicon-ngrok-original"
  },
  {
    "id": "ngrx",
    "label": "Ngrx",
    "iconClass": "devicon-ngrx-plain"
  },
  {
    "id": "nhibernate",
    "label": "Nhibernate",
    "iconClass": "devicon-nhibernate-plain"
  },
  {
    "id": "nim",
    "label": "Nim",
    "iconClass": "devicon-nim-plain"
  },
  {
    "id": "nimble",
    "label": "Nimble",
    "iconClass": "devicon-nimble-plain"
  },
  {
    "id": "nixos",
    "label": "Nixos",
    "iconClass": "devicon-nixos-plain"
  },
  {
    "id": "nodejs",
    "label": "Nodejs",
    "iconClass": "devicon-nodejs-plain"
  },
  {
    "id": "nodemon",
    "label": "Nodemon",
    "iconClass": "devicon-nodemon-plain"
  },
  {
    "id": "nodered",
    "label": "Nodered",
    "iconClass": "devicon-nodered-plain"
  },
  {
    "id": "nodewebkit",
    "label": "Nodewebkit",
    "iconClass": "devicon-nodewebkit-plain"
  },
  {
    "id": "nomad",
    "label": "Nomad",
    "iconClass": "devicon-nomad-original"
  },
  {
    "id": "norg",
    "label": "Norg",
    "iconClass": "devicon-norg-plain"
  },
  {
    "id": "notion",
    "label": "Notion",
    "iconClass": "devicon-notion-plain"
  },
  {
    "id": "npm",
    "label": "Npm",
    "iconClass": "devicon-npm-plain"
  },
  {
    "id": "npss",
    "label": "Npss",
    "iconClass": "devicon-npss-plain"
  },
  {
    "id": "nuget",
    "label": "Nuget",
    "iconClass": "devicon-nuget-original"
  },
  {
    "id": "numpy",
    "label": "Numpy",
    "iconClass": "devicon-numpy-plain"
  },
  {
    "id": "nuxt",
    "label": "Nuxt",
    "iconClass": "devicon-nuxt-original"
  },
  {
    "id": "nuxtjs",
    "label": "Nuxtjs",
    "iconClass": "devicon-nuxtjs-plain"
  },
  {
    "id": "oauth",
    "label": "Oauth",
    "iconClass": "devicon-oauth-plain"
  },
  {
    "id": "objectivec",
    "label": "Objectivec",
    "iconClass": "devicon-objectivec-plain"
  },
  {
    "id": "ocaml",
    "label": "Ocaml",
    "iconClass": "devicon-ocaml-plain"
  },
  {
    "id": "ohmyzsh",
    "label": "Ohmyzsh",
    "iconClass": "devicon-ohmyzsh-plain"
  },
  {
    "id": "okta",
    "label": "Okta",
    "iconClass": "devicon-okta-plain"
  },
  {
    "id": "openal",
    "label": "Openal",
    "iconClass": "devicon-openal-plain"
  },
  {
    "id": "openapi",
    "label": "Openapi",
    "iconClass": "devicon-openapi-plain"
  },
  {
    "id": "opencl",
    "label": "Opencl",
    "iconClass": "devicon-opencl-plain"
  },
  {
    "id": "opencv",
    "label": "Opencv",
    "iconClass": "devicon-opencv-plain"
  },
  {
    "id": "opengl",
    "label": "Opengl",
    "iconClass": "devicon-opengl-plain"
  },
  {
    "id": "openstack",
    "label": "Openstack",
    "iconClass": "devicon-openstack-original"
  },
  {
    "id": "opensuse",
    "label": "Opensuse",
    "iconClass": "devicon-opensuse-original"
  },
  {
    "id": "opentelemetry",
    "label": "Opentelemetry",
    "iconClass": "devicon-opentelemetry-plain"
  },
  {
    "id": "opera",
    "label": "Opera",
    "iconClass": "devicon-opera-plain"
  },
  {
    "id": "oracle",
    "label": "Oracle",
    "iconClass": "devicon-oracle-original"
  },
  {
    "id": "ory",
    "label": "Ory",
    "iconClass": "devicon-ory-original"
  },
  {
    "id": "p5js",
    "label": "P5js",
    "iconClass": "devicon-p5js-original"
  },
  {
    "id": "packer",
    "label": "Packer",
    "iconClass": "devicon-packer-plain"
  },
  {
    "id": "pandas",
    "label": "Pandas",
    "iconClass": "devicon-pandas-plain"
  },
  {
    "id": "passport",
    "label": "Passport",
    "iconClass": "devicon-passport-plain"
  },
  {
    "id": "perl",
    "label": "Perl",
    "iconClass": "devicon-perl-plain"
  },
  {
    "id": "pfsense",
    "label": "Pfsense",
    "iconClass": "devicon-pfsense-original"
  },
  {
    "id": "phalcon",
    "label": "Phalcon",
    "iconClass": "devicon-phalcon-plain"
  },
  {
    "id": "phoenix",
    "label": "Phoenix",
    "iconClass": "devicon-phoenix-original"
  },
  {
    "id": "photonengine",
    "label": "Photonengine",
    "iconClass": "devicon-photonengine-plain"
  },
  {
    "id": "photoshop",
    "label": "Photoshop",
    "iconClass": "devicon-photoshop-plain"
  },
  {
    "id": "php",
    "label": "Php",
    "iconClass": "devicon-php-plain"
  },
  {
    "id": "phpstorm",
    "label": "Phpstorm",
    "iconClass": "devicon-phpstorm-plain"
  },
  {
    "id": "pixijs",
    "label": "Pixijs",
    "iconClass": "devicon-pixijs-plain"
  },
  {
    "id": "playwright",
    "label": "Playwright",
    "iconClass": "devicon-playwright-plain"
  },
  {
    "id": "plotly",
    "label": "Plotly",
    "iconClass": "devicon-plotly-plain"
  },
  {
    "id": "pm2",
    "label": "Pm2",
    "iconClass": "devicon-pm2-plain"
  },
  {
    "id": "pnpm",
    "label": "Pnpm",
    "iconClass": "devicon-pnpm-plain"
  },
  {
    "id": "podman",
    "label": "Podman",
    "iconClass": "devicon-podman-plain"
  },
  {
    "id": "poetry",
    "label": "Poetry",
    "iconClass": "devicon-poetry-plain"
  },
  {
    "id": "polygon",
    "label": "Polygon",
    "iconClass": "devicon-polygon-plain"
  },
  {
    "id": "portainer",
    "label": "Portainer",
    "iconClass": "devicon-portainer-original"
  },
  {
    "id": "postcss",
    "label": "Postcss",
    "iconClass": "devicon-postcss-original"
  },
  {
    "id": "postgresql",
    "label": "Postgresql",
    "iconClass": "devicon-postgresql-plain"
  },
  {
    "id": "postman",
    "label": "Postman",
    "iconClass": "devicon-postman-plain"
  },
  {
    "id": "powershell",
    "label": "Powershell",
    "iconClass": "devicon-powershell-plain"
  },
  {
    "id": "premierepro",
    "label": "Premierepro",
    "iconClass": "devicon-premierepro-plain"
  },
  {
    "id": "primeng",
    "label": "Primeng",
    "iconClass": "devicon-primeng-plain"
  },
  {
    "id": "prisma",
    "label": "Prisma",
    "iconClass": "devicon-prisma-original"
  },
  {
    "id": "processing",
    "label": "Processing",
    "iconClass": "devicon-processing-plain"
  },
  {
    "id": "processwire",
    "label": "Processwire",
    "iconClass": "devicon-processwire-original"
  },
  {
    "id": "prolog",
    "label": "Prolog",
    "iconClass": "devicon-prolog-plain"
  },
  {
    "id": "prometheus",
    "label": "Prometheus",
    "iconClass": "devicon-prometheus-original"
  },
  {
    "id": "protractor",
    "label": "Protractor",
    "iconClass": "devicon-protractor-plain"
  },
  {
    "id": "proxmox",
    "label": "Proxmox",
    "iconClass": "devicon-proxmox-plain"
  },
  {
    "id": "pug",
    "label": "Pug",
    "iconClass": "devicon-pug-plain"
  },
  {
    "id": "pulsar",
    "label": "Pulsar",
    "iconClass": "devicon-pulsar-original"
  },
  {
    "id": "pulumi",
    "label": "Pulumi",
    "iconClass": "devicon-pulumi-plain"
  },
  {
    "id": "puppeteer",
    "label": "Puppeteer",
    "iconClass": "devicon-puppeteer-plain"
  },
  {
    "id": "purescript",
    "label": "Purescript",
    "iconClass": "devicon-purescript-original"
  },
  {
    "id": "putty",
    "label": "Putty",
    "iconClass": "devicon-putty-plain"
  },
  {
    "id": "pycharm",
    "label": "Pycharm",
    "iconClass": "devicon-pycharm-plain"
  },
  {
    "id": "pypi",
    "label": "Pypi",
    "iconClass": "devicon-pypi-plain"
  },
  {
    "id": "pyscript",
    "label": "Pyscript",
    "iconClass": "devicon-pyscript-plain-wordmark"
  },
  {
    "id": "pytest",
    "label": "Pytest",
    "iconClass": "devicon-pytest-plain"
  },
  {
    "id": "python",
    "label": "Python",
    "iconClass": "devicon-python-plain"
  },
  {
    "id": "pytorch",
    "label": "Pytorch",
    "iconClass": "devicon-pytorch-original"
  },
  {
    "id": "qodana",
    "label": "Qodana",
    "iconClass": "devicon-qodana-plain"
  },
  {
    "id": "qt",
    "label": "Qt",
    "iconClass": "devicon-qt-original"
  },
  {
    "id": "qtest",
    "label": "Qtest",
    "iconClass": "devicon-qtest-original"
  },
  {
    "id": "quarkus",
    "label": "Quarkus",
    "iconClass": "devicon-quarkus-plain"
  },
  {
    "id": "quasar",
    "label": "Quasar",
    "iconClass": "devicon-quasar-plain"
  },
  {
    "id": "qwik",
    "label": "Qwik",
    "iconClass": "devicon-qwik-plain"
  },
  {
    "id": "r",
    "label": "R",
    "iconClass": "devicon-r-plain"
  },
  {
    "id": "rabbitmq",
    "label": "Rabbitmq",
    "iconClass": "devicon-rabbitmq-original"
  },
  {
    "id": "racket",
    "label": "Racket",
    "iconClass": "devicon-racket-plain"
  },
  {
    "id": "radstudio",
    "label": "Radstudio",
    "iconClass": "devicon-radstudio-plain"
  },
  {
    "id": "rails",
    "label": "Rails",
    "iconClass": "devicon-rails-plain"
  },
  {
    "id": "railway",
    "label": "Railway",
    "iconClass": "devicon-railway-original"
  },
  {
    "id": "rancher",
    "label": "Rancher",
    "iconClass": "devicon-rancher-original"
  },
  {
    "id": "raspberrypi",
    "label": "Raspberrypi",
    "iconClass": "devicon-raspberrypi-plain"
  },
  {
    "id": "reach",
    "label": "Reach",
    "iconClass": "devicon-reach-plain"
  },
  {
    "id": "react",
    "label": "React",
    "iconClass": "devicon-react-original"
  },
  {
    "id": "reactbootstrap",
    "label": "Reactbootstrap",
    "iconClass": "devicon-reactbootstrap-original"
  },
  {
    "id": "reactnative",
    "label": "Reactnative",
    "iconClass": "devicon-reactnative-original"
  },
  {
    "id": "reactnavigation",
    "label": "Reactnavigation",
    "iconClass": "devicon-reactnavigation-original"
  },
  {
    "id": "reactrouter",
    "label": "Reactrouter",
    "iconClass": "devicon-reactrouter-plain"
  },
  {
    "id": "readthedocs",
    "label": "Readthedocs",
    "iconClass": "devicon-readthedocs-original"
  },
  {
    "id": "realm",
    "label": "Realm",
    "iconClass": "devicon-realm-plain"
  },
  {
    "id": "rect",
    "label": "Rect",
    "iconClass": "devicon-rect-plain"
  },
  {
    "id": "redhat",
    "label": "Redhat",
    "iconClass": "devicon-redhat-plain"
  },
  {
    "id": "redis",
    "label": "Redis",
    "iconClass": "devicon-redis-plain"
  },
  {
    "id": "redux",
    "label": "Redux",
    "iconClass": "devicon-redux-original"
  },
  {
    "id": "reflex",
    "label": "Reflex",
    "iconClass": "devicon-reflex-plain"
  },
  {
    "id": "remix",
    "label": "Remix",
    "iconClass": "devicon-remix-original"
  },
  {
    "id": "renpy",
    "label": "Renpy",
    "iconClass": "devicon-renpy-plain"
  },
  {
    "id": "replit",
    "label": "Replit",
    "iconClass": "devicon-replit-original"
  },
  {
    "id": "rexx",
    "label": "Rexx",
    "iconClass": "devicon-rexx-plain"
  },
  {
    "id": "rider",
    "label": "Rider",
    "iconClass": "devicon-rider-plain"
  },
  {
    "id": "rocksdb",
    "label": "Rocksdb",
    "iconClass": "devicon-rocksdb-plain"
  },
  {
    "id": "rockylinux",
    "label": "Rockylinux",
    "iconClass": "devicon-rockylinux-original"
  },
  {
    "id": "rollup",
    "label": "Rollup",
    "iconClass": "devicon-rollup-plain"
  },
  {
    "id": "ros",
    "label": "Ros",
    "iconClass": "devicon-ros-original"
  },
  {
    "id": "rspec",
    "label": "Rspec",
    "iconClass": "devicon-rspec-plain"
  },
  {
    "id": "rstudio",
    "label": "Rstudio",
    "iconClass": "devicon-rstudio-plain"
  },
  {
    "id": "ruby",
    "label": "Ruby",
    "iconClass": "devicon-ruby-plain"
  },
  {
    "id": "rubymine",
    "label": "Rubymine",
    "iconClass": "devicon-rubymine-plain"
  },
  {
    "id": "rust",
    "label": "Rust",
    "iconClass": "devicon-rust-original"
  },
  {
    "id": "rxjs",
    "label": "Rxjs",
    "iconClass": "devicon-rxjs-plain"
  },
  {
    "id": "safari",
    "label": "Safari",
    "iconClass": "devicon-safari-plain"
  },
  {
    "id": "salesforce",
    "label": "Salesforce",
    "iconClass": "devicon-salesforce-plain"
  },
  {
    "id": "sanity",
    "label": "Sanity",
    "iconClass": "devicon-sanity-plain"
  },
  {
    "id": "sass",
    "label": "Sass",
    "iconClass": "devicon-sass-original"
  },
  {
    "id": "scala",
    "label": "Scala",
    "iconClass": "devicon-scala-plain"
  },
  {
    "id": "scalingo",
    "label": "Scalingo",
    "iconClass": "devicon-scalingo-plain"
  },
  {
    "id": "scikitlearn",
    "label": "Scikitlearn",
    "iconClass": "devicon-scikitlearn-plain"
  },
  {
    "id": "sdl",
    "label": "Sdl",
    "iconClass": "devicon-sdl-plain"
  },
  {
    "id": "selenium",
    "label": "Selenium",
    "iconClass": "devicon-selenium-original"
  },
  {
    "id": "sema",
    "label": "Sema",
    "iconClass": "devicon-sema-original"
  },
  {
    "id": "sentry",
    "label": "Sentry",
    "iconClass": "devicon-sentry-original"
  },
  {
    "id": "sequelize",
    "label": "Sequelize",
    "iconClass": "devicon-sequelize-plain"
  },
  {
    "id": "shopware",
    "label": "Shopware",
    "iconClass": "devicon-shopware-original"
  },
  {
    "id": "shotgrid",
    "label": "Shotgrid",
    "iconClass": "devicon-shotgrid-plain"
  },
  {
    "id": "sketch",
    "label": "Sketch",
    "iconClass": "devicon-sketch-plain"
  },
  {
    "id": "slack",
    "label": "Slack",
    "iconClass": "devicon-slack-plain"
  },
  {
    "id": "socketio",
    "label": "Socketio",
    "iconClass": "devicon-socketio-original"
  },
  {
    "id": "solidity",
    "label": "Solidity",
    "iconClass": "devicon-solidity-plain"
  },
  {
    "id": "solidjs",
    "label": "Solidjs",
    "iconClass": "devicon-solidjs-plain"
  },
  {
    "id": "sonarqube",
    "label": "Sonarqube",
    "iconClass": "devicon-sonarqube-original"
  },
  {
    "id": "sourceengine",
    "label": "Sourceengine",
    "iconClass": "devicon-sourceengine-plain"
  },
  {
    "id": "sourcetree",
    "label": "Sourcetree",
    "iconClass": "devicon-sourcetree-original"
  },
  {
    "id": "spack",
    "label": "Spack",
    "iconClass": "devicon-spack-plain"
  },
  {
    "id": "spicedb",
    "label": "Spicedb",
    "iconClass": "devicon-spicedb-plain"
  },
  {
    "id": "splunk",
    "label": "Splunk",
    "iconClass": "devicon-splunk-original-wordmark"
  },
  {
    "id": "spring",
    "label": "Spring",
    "iconClass": "devicon-spring-original"
  },
  {
    "id": "spss",
    "label": "Spss",
    "iconClass": "devicon-spss-plain"
  },
  {
    "id": "spyder",
    "label": "Spyder",
    "iconClass": "devicon-spyder-plain"
  },
  {
    "id": "sqlalchemy",
    "label": "Sqlalchemy",
    "iconClass": "devicon-sqlalchemy-plain"
  },
  {
    "id": "sqldeveloper",
    "label": "Sqldeveloper",
    "iconClass": "devicon-sqldeveloper-plain"
  },
  {
    "id": "sqlite",
    "label": "Sqlite",
    "iconClass": "devicon-sqlite-plain"
  },
  {
    "id": "ssh",
    "label": "Ssh",
    "iconClass": "devicon-ssh-original"
  },
  {
    "id": "stackblitz",
    "label": "Stackblitz",
    "iconClass": "devicon-stackblitz-original"
  },
  {
    "id": "stackoverflow",
    "label": "Stackoverflow",
    "iconClass": "devicon-stackoverflow-plain"
  },
  {
    "id": "stata",
    "label": "Stata",
    "iconClass": "devicon-stata-original-wordmark"
  },
  {
    "id": "stenciljs",
    "label": "Stenciljs",
    "iconClass": "devicon-stenciljs-plain"
  },
  {
    "id": "storybook",
    "label": "Storybook",
    "iconClass": "devicon-storybook-plain"
  },
  {
    "id": "streamlit",
    "label": "Streamlit",
    "iconClass": "devicon-streamlit-plain"
  },
  {
    "id": "styledcomponents",
    "label": "Styledcomponents",
    "iconClass": "devicon-styledcomponents-plain"
  },
  {
    "id": "stylus",
    "label": "Stylus",
    "iconClass": "devicon-stylus-original"
  },
  {
    "id": "subversion",
    "label": "Subversion",
    "iconClass": "devicon-subversion-original"
  },
  {
    "id": "sulu",
    "label": "Sulu",
    "iconClass": "devicon-sulu-original"
  },
  {
    "id": "supabase",
    "label": "Supabase",
    "iconClass": "devicon-supabase-plain"
  },
  {
    "id": "surrealdb",
    "label": "Surrealdb",
    "iconClass": "devicon-surrealdb-plain"
  },
  {
    "id": "svelte",
    "label": "Svelte",
    "iconClass": "devicon-svelte-plain"
  },
  {
    "id": "svgo",
    "label": "Svgo",
    "iconClass": "devicon-svgo-plain"
  },
  {
    "id": "swagger",
    "label": "Swagger",
    "iconClass": "devicon-swagger-plain"
  },
  {
    "id": "swift",
    "label": "Swift",
    "iconClass": "devicon-swift-plain"
  },
  {
    "id": "swiper",
    "label": "Swiper",
    "iconClass": "devicon-swiper-original"
  },
  {
    "id": "symfony",
    "label": "Symfony",
    "iconClass": "devicon-symfony-original"
  },
  {
    "id": "tailwindcss",
    "label": "Tailwindcss",
    "iconClass": "devicon-tailwindcss-original"
  },
  {
    "id": "talos",
    "label": "Talos",
    "iconClass": "devicon-talos-plain"
  },
  {
    "id": "tauri",
    "label": "Tauri",
    "iconClass": "devicon-tauri-plain"
  },
  {
    "id": "teleport",
    "label": "Teleport",
    "iconClass": "devicon-teleport-original"
  },
  {
    "id": "tensorflow",
    "label": "Tensorflow",
    "iconClass": "devicon-tensorflow-original"
  },
  {
    "id": "terraform",
    "label": "Terraform",
    "iconClass": "devicon-terraform-plain"
  },
  {
    "id": "terramate",
    "label": "Terramate",
    "iconClass": "devicon-terramate-original"
  },
  {
    "id": "tex",
    "label": "Tex",
    "iconClass": "devicon-tex-original"
  },
  {
    "id": "thealgorithms",
    "label": "Thealgorithms",
    "iconClass": "devicon-thealgorithms-plain"
  },
  {
    "id": "threedsmax",
    "label": "Threedsmax",
    "iconClass": "devicon-threedsmax-plain"
  },
  {
    "id": "threejs",
    "label": "Threejs",
    "iconClass": "devicon-threejs-original"
  },
  {
    "id": "thymeleaf",
    "label": "Thymeleaf",
    "iconClass": "devicon-thymeleaf-plain"
  },
  {
    "id": "titaniumsdk",
    "label": "Titaniumsdk",
    "iconClass": "devicon-titaniumsdk-original"
  },
  {
    "id": "tmux",
    "label": "Tmux",
    "iconClass": "devicon-tmux-plain"
  },
  {
    "id": "tomcat",
    "label": "Tomcat",
    "iconClass": "devicon-tomcat-line"
  },
  {
    "id": "tortoisegit",
    "label": "Tortoisegit",
    "iconClass": "devicon-tortoisegit-plain"
  },
  {
    "id": "towergit",
    "label": "Towergit",
    "iconClass": "devicon-towergit-plain"
  },
  {
    "id": "traefikmesh",
    "label": "Traefikmesh",
    "iconClass": "devicon-traefikmesh-original"
  },
  {
    "id": "traefikproxy",
    "label": "Traefikproxy",
    "iconClass": "devicon-traefikproxy-original"
  },
  {
    "id": "travis",
    "label": "Travis",
    "iconClass": "devicon-travis-plain"
  },
  {
    "id": "trello",
    "label": "Trello",
    "iconClass": "devicon-trello-plain"
  },
  {
    "id": "trpc",
    "label": "Trpc",
    "iconClass": "devicon-trpc-plain"
  },
  {
    "id": "turbo",
    "label": "Turbo",
    "iconClass": "devicon-turbo-original"
  },
  {
    "id": "twilio",
    "label": "Twilio",
    "iconClass": "devicon-twilio-original"
  },
  {
    "id": "twitter",
    "label": "Twitter",
    "iconClass": "devicon-twitter-original"
  },
  {
    "id": "typescript",
    "label": "Typescript",
    "iconClass": "devicon-typescript-plain"
  },
  {
    "id": "typo3",
    "label": "Typo3",
    "iconClass": "devicon-typo3-original"
  },
  {
    "id": "ubuntu",
    "label": "Ubuntu",
    "iconClass": "devicon-ubuntu-plain"
  },
  {
    "id": "unifiedmodelinglanguage",
    "label": "Unifiedmodelinglanguage",
    "iconClass": "devicon-unifiedmodelinglanguage-plain"
  },
  {
    "id": "unity",
    "label": "Unity",
    "iconClass": "devicon-unity-plain"
  },
  {
    "id": "unix",
    "label": "Unix",
    "iconClass": "devicon-unix-original"
  },
  {
    "id": "unrealengine",
    "label": "Unrealengine",
    "iconClass": "devicon-unrealengine-original"
  },
  {
    "id": "uwsgi",
    "label": "Uwsgi",
    "iconClass": "devicon-uwsgi-plain"
  },
  {
    "id": "v8",
    "label": "V8",
    "iconClass": "devicon-v8-plain"
  },
  {
    "id": "vaadin",
    "label": "Vaadin",
    "iconClass": "devicon-vaadin-original"
  },
  {
    "id": "vagrant",
    "label": "Vagrant",
    "iconClass": "devicon-vagrant-plain"
  },
  {
    "id": "vala",
    "label": "Vala",
    "iconClass": "devicon-vala-plain"
  },
  {
    "id": "vault",
    "label": "Vault",
    "iconClass": "devicon-vault-original"
  },
  {
    "id": "veevalidate",
    "label": "Veevalidate",
    "iconClass": "devicon-veevalidate-original"
  },
  {
    "id": "vercel",
    "label": "Vercel",
    "iconClass": "devicon-vercel-original"
  },
  {
    "id": "vertx",
    "label": "Vertx",
    "iconClass": "devicon-vertx-plain"
  },
  {
    "id": "vim",
    "label": "Vim",
    "iconClass": "devicon-vim-plain"
  },
  {
    "id": "visualbasic",
    "label": "Visualbasic",
    "iconClass": "devicon-visualbasic-plain"
  },
  {
    "id": "visualstudio",
    "label": "Visualstudio",
    "iconClass": "devicon-visualstudio-plain"
  },
  {
    "id": "vite",
    "label": "Vite",
    "iconClass": "devicon-vite-original"
  },
  {
    "id": "vitejs",
    "label": "Vitejs",
    "iconClass": "devicon-vitejs-plain"
  },
  {
    "id": "vitess",
    "label": "Vitess",
    "iconClass": "devicon-vitess-plain"
  },
  {
    "id": "vitest",
    "label": "Vitest",
    "iconClass": "devicon-vitest-plain"
  },
  {
    "id": "vscode",
    "label": "Vscode",
    "iconClass": "devicon-vscode-plain"
  },
  {
    "id": "vscodium",
    "label": "Vscodium",
    "iconClass": "devicon-vscodium-plain"
  },
  {
    "id": "vsphere",
    "label": "Vsphere",
    "iconClass": "devicon-vsphere-plain"
  },
  {
    "id": "vuejs",
    "label": "Vuejs",
    "iconClass": "devicon-vuejs-plain"
  },
  {
    "id": "vuestorefront",
    "label": "Vuestorefront",
    "iconClass": "devicon-vuestorefront-plain"
  },
  {
    "id": "vuetify",
    "label": "Vuetify",
    "iconClass": "devicon-vuetify-plain"
  },
  {
    "id": "vulkan",
    "label": "Vulkan",
    "iconClass": "devicon-vulkan-original"
  },
  {
    "id": "vyper",
    "label": "Vyper",
    "iconClass": "devicon-vyper-original"
  },
  {
    "id": "waku",
    "label": "Waku",
    "iconClass": "devicon-waku-plain"
  },
  {
    "id": "wasm",
    "label": "Wasm",
    "iconClass": "devicon-wasm-original"
  },
  {
    "id": "web3js",
    "label": "Web3js",
    "iconClass": "devicon-web3js-plain"
  },
  {
    "id": "webflow",
    "label": "Webflow",
    "iconClass": "devicon-webflow-original"
  },
  {
    "id": "webgpu",
    "label": "Webgpu",
    "iconClass": "devicon-webgpu-plain"
  },
  {
    "id": "weblate",
    "label": "Weblate",
    "iconClass": "devicon-weblate-plain"
  },
  {
    "id": "webpack",
    "label": "Webpack",
    "iconClass": "devicon-webpack-plain"
  },
  {
    "id": "webstorm",
    "label": "Webstorm",
    "iconClass": "devicon-webstorm-plain"
  },
  {
    "id": "windows11",
    "label": "Windows11",
    "iconClass": "devicon-windows11-original"
  },
  {
    "id": "windows8",
    "label": "Windows8",
    "iconClass": "devicon-windows8-original"
  },
  {
    "id": "wolfram",
    "label": "Wolfram",
    "iconClass": "devicon-wolfram-plain"
  },
  {
    "id": "woocommerce",
    "label": "Woocommerce",
    "iconClass": "devicon-woocommerce-plain"
  },
  {
    "id": "wordpress",
    "label": "Wordpress",
    "iconClass": "devicon-wordpress-plain"
  },
  {
    "id": "xamarin",
    "label": "Xamarin",
    "iconClass": "devicon-xamarin-original"
  },
  {
    "id": "xcode",
    "label": "Xcode",
    "iconClass": "devicon-xcode-plain"
  },
  {
    "id": "xd",
    "label": "Xd",
    "iconClass": "devicon-xd-plain"
  },
  {
    "id": "xml",
    "label": "Xml",
    "iconClass": "devicon-xml-plain"
  },
  {
    "id": "yaml",
    "label": "Yaml",
    "iconClass": "devicon-yaml-plain"
  },
  {
    "id": "yarn",
    "label": "Yarn",
    "iconClass": "devicon-yarn-original"
  },
  {
    "id": "yii",
    "label": "Yii",
    "iconClass": "devicon-yii-plain"
  },
  {
    "id": "yugabytedb",
    "label": "Yugabytedb",
    "iconClass": "devicon-yugabytedb-plain"
  },
  {
    "id": "yunohost",
    "label": "Yunohost",
    "iconClass": "devicon-yunohost-plain"
  },
  {
    "id": "zend",
    "label": "Zend",
    "iconClass": "devicon-zend-original"
  },
  {
    "id": "zig",
    "label": "Zig",
    "iconClass": "devicon-zig-original"
  }
];
