/** ATS platforms removed from the product ATS list (from felovy-search). */
export const EXCLUDED_PLATFORM_SLUGS = new Set([
  'workable',
  'personio_de',
  'personio_com',
  'softgarden_io',
  'teamtailor_com',
  'recruitee_com',
  'werecruit_io',
  'factorialhr_com',
  'pinpointhq_com',
  'traffit_com',
  'hibob_com',
  'zohorecruit_eu',
  'zohorecruit_com',
  'careers_page_com',
  'recruitify_ai',
  'freshteam_com',
  'rippling_com',
  'gem_com',
  'trinethire_com',
  'jobvite_com',
  'prismhr_hire_com',
  'trakstar_com',
  'applytojob_com',
]);
